reportefacturaelectronica
Tokulabs/inventory_api pull request #48
Opened 2024-05-10 06:02 UTC by cadsx

2024-05-11 02:19 UTC, ndf1511 requested changes

2024-05-11 02:19 UTC, ndf1511 commented on app_control/views.py
> +        start_date = request.data.get("start_date", None)
timestamp instead of dates

2024-05-11 02:19 UTC, ndf1511 commented on app_control/views.py
> +        start_date = request.data.get("start_date", None)
Move dates to start of function. line 873

2024-05-11 02:19 UTC, ndf1511 commented on app_control/views.py
> +        response['Content-Disposition'] = 'attachment; filename="DocumentosVentasEncabezadosMovimientoInventarioWO.xlsx"'
Put dates in filename

2024-05-11 02:19 UTC, ndf1511 commented on app_control/views.py
> +            .filter(created_at__date__gte=start_date, created_at__date__lte=end_date)
not date,  timestamp

2024-05-11 02:19 UTC, ndf1511 commented on app_control/views.py
> +            .filter(is_override=False)
.filter(invoice_items__is_gift=False)

2024-05-11 02:19 UTC, ndf1511 commented on inventory_api/utils.py
> +    row_titles = ["Empresa","Tipo Documento","prefijo","DocumentoNúmero","Fecha","Tercero Interno","Tercero Externo","Nota",
column_titles

2024-05-11 02:19 UTC, ndf1511 commented on inventory_api/utils.py
> +    for cell in ws[get_column_letter(5)]:
for cell in  [ws[], ws[]]

2024-05-11 18:45 UTC, oskarkos commented on app_control/urls.py
> +    InvoicesReportExporter, CustomerView, InvoicePainterView, FacturaElectronicaExporter
Name in english

2024-05-16 01:49 UTC, ndf1511 approved these changes

2024-05-16 20:33 UTC, merged